dist: trusty
sudo: false
language: php
php:
- '7.1'
before_install:
- pyenv versions
- pyenv global system 3.5
- echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- cp .env.example .env
- mkdir -p bootstrap/cache
- mkdir -p storage/app/public
- mkdir -p storage/framework/cache
- mkdir -p storage/framework/sessions
- mkdir -p storage/framework/views
- mkdir -p storage/logs
install:
- pip3 install ansible
- composer install --prefer-dist
- npm install -g yarn
- yarn
before_script:
- php artisan key:generate
- echo $ANSIBLE_VAULT > playbooks/ansible_vault
script:
- "( cd playbooks && ./tests.sh )"
- yarn run build
- yarn run lint
- phpunit
after_success:
- openssl aes-256-cbc -K $encrypted_332711f93af1_key -iv $encrypted_332711f93af1_iv
  -in scripts/key/deploy-key.enc -out scripts/key/deploy-key -d
- chmod 600 scripts/key/deploy-key
- ./scripts/deploy.sh
addons:
  ssh_known_hosts: plugboard.xyz
cache:
  pip: true
  directories:
  - node_modules
  - vendor
  - $HOME/.cache/yarn
  - $HOME/.composer/cache/files
env:
  global:
    secure: du8cIaQlYDoo8/zPLK2vWbNt3l+4q4fz217ern0mg08YtJqftMuA43MXs5YogiJeKSRtz8gmpGa+FSo1m+AkCbshmS0Ha48mQ8V4l99ghR8GSxWgPAtuZaMFu4gidnrpNEcXBv8OZ6hatHTG4TV35hiX+CK9Qo1qkPFvWILU+Ln5eGyLj+qbvbokTjf4wwLTiQP5wC0p7AP5Y/DNzV2XnAe0jrmyX/OLnzRlFiKtwb6E1u0QHJ6GFYt7uR8RS/1GLFImajlJgDhVa3W6U0WWcMZPQhA/iMLHN25U8BNbd+TrfLIw/TTl+OCqI0aQosXbVl6eauDK6R9gy1HOeaEQHZQ6GRwEx8cVP89J1eiHyjjGZk6IettJhasvCgr1k+0b9d98qsCG5YPZ/HXbkxT1JQGjIwaDRVcUeRIaYwigf0fwGkJEDsbP2Lpr2UYK6Rya2tecPEOGQbWDGZHGWIv9F3szRMssYEj1S+MkL8euTqbXZ7yjuM+Bs+6lN8Miey8ywOEjtb2wq1B7QSN14K66Lq6hXbzgYEzSVaNKEa5UFF2uRF81bpq4ZVUObQmwzo5RcRS2pYBnsjFeDXhlATFu/hCJAizV7sg8vGqqTkc4GbHT5FLroY0n+U0XshEPw9993VNQq70wACRke8W+FxUwp1rZMyD7+wLBfmb8NE6lJVg=
