---
- name: Deploy apps
  user: root
  hosts: all
  vars:
    app_deploy_script_path: '{{playbook_dir}}/../../scripts'
  roles:
    - { role: app, app: '{{apps.plugboard_prod}}', nginx_default: true }
