---
- name: Setup of server
  user: root
  hosts: all
  roles:
    - common
    - firewall
    - ntp
    - letsencrypt
    - nodejs
    - yarn
    - php
    - nginx
    - mysql
    - mongodb
    - redis
