---
- name: install nginx
  apt: name=nginx state=latest
  tags: nginx

- name: copy ssl-params.conf snippet
  copy: src=ssl-params.conf dest=/etc/nginx/snippets/ssl-params.conf
  notify:
    - reload nginx
  tags: nginx

- name: disable default site
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify:
    - reload nginx
  tags: nginx

- name: enable and start nginx
  systemd: name=nginx state=started enabled=yes
  tags: nginx
